### ISSUE TITLE
can't use addon with less project

### ISSUE THREAD

**Issue by jaichandra** [aexmachina/ember-cli-sass#104]
Im trying to add SASS support to already existing project that uses LESS files (with ember-cli-less). I'm getting below error on build:

----
File not found: /app/styles/app.scss
in any of the following include paths:
  .../tmp/sass_compiler-input_base_path-50K8SQUz.tmp/0
Error: File not found: /app/styles/app.scss
in any of the following include paths:
  .../tmp/sass_compiler-input_base_path-50K8SQUz.tmp/0
    at Object.findFileSync (.../node_modules/include-path-searcher/index.js:12:9)
    at SassCompiler.build (.../node_modules/ember-cli-sass/node_modules/broccoli-sass-source-maps/index.js:62:31)
    at .../node_modules/ember-cli-sass/node_modules/broccoli-sass-source-maps/node_modules/broccoli-caching-writer/index.js:152:21
    at lib$rsvp$$internal$$tryCatch (.../node_modules/rsvp/dist/rsvp.js:493:16)
    at lib$rsvp$$internal$$invokeCallback (.../node_modules/rsvp/dist/rsvp.js:505:17)
    at lib$rsvp$$internal$$publish (.../node_modules/rsvp/dist/rsvp.js:476:11)
    at lib$rsvp$asap$$flush (.../node_modules/rsvp/dist/rsvp.js:1198:9)
    at nextTickCallbackWith0Args (node.js:433:9)
    at process._tickCallback (node.js:362:13)

I have just scrubbed the folder paths in above trace with '.../'.

**Comment by aexmachina** [comment]
Does it still happen if you remove ember-cli-less from package.json?

**Comment by jaichandra** [comment]
If I remove ember-cli-less, it works fine. But I need to keep the plugin as I have LESS files.

**Comment by aexmachina** [comment]
That's not the question. See above ^

**Comment by aexmachina** [comment]
@stefanpenner any ideas about this?

**Comment by jaichandra** [comment]
removing ember-cli-less takes away the error. But the app throws runtime js errors. Im also using ember-cli-bless, and it looks like that addon is failing. I see that <appname>-blessed1.css file is missing and browser is throwing a 404 exception there.

**Comment by aexmachina** [comment]
Closing due to inactivity, feel free to reopen.

**Comment by Duder-onomy** [comment]
@aexmachina This is still an issue. Running into this right now. 
We are currently moving from less to scss in a legacy ember app, we cannot have them both running at the same time. 

I believe this to be the same issue seen in : https://github.com/aexmachina/ember-cli-sass/issues/67

If I remove `ember-cli-less` this repo works fine.
If I remove `ember-cli-sass` this repo works fine. 
If I have them both in the app, the whole thing breaks with identical error referenced above:

```
Build Error (SassCompiler)

File not found: /app/styles/app.scss
in any of the following include paths:
  /project/tmp/sass_compiler-input_base_path-wWHtMVOF.tmp/0
  /project/tmp/sass_compiler-input_base_path-wWHtMVOF.tmp/1
```

Any ideas?  Eventually we will be removing ember-cli-less.... but I would love to do it slowly instead of all at once?

**Comment by aexmachina** [comment]
I'm afraid that I can't shed any light on this and I'm not using this project, so I can offer you only my best wishes!

**Comment by Duder-onomy** [comment]
Bummer. No worries I guess. I will blame it on LESS
we should all use less Less
