### ISSUE TITLE
Sass imports not working as expected

### ISSUE THREAD

**Issue by chanakairugal** [aexmachina/ember-cli-sass#126]
Im trying to use **susy** and **breakpoint** in layout scss file. 
`@import "../../node_modules/susy/sass/susy";`

but the build fails with: 
```File: E:/___temp-projects/TBXSurfCSS/tmp/sassplugin-input_base_path-jREz02B2.tmp/0/src/demo-app/base-layout.scss (9)
The Broccoli Plugin: [SASSPlugin] failed with:
Error: File to import not found or unreadable: sass/susy
Parent style sheet: E:/___temp-projects/TBXSurfCSS/tmp/sassplugin-input_base_path-jREz02B2.tmp/0/src/demo-app/base-layout.scss
    at Object.module.exports.renderSync (E:\___temp-projects\TBXSurfCSS\node_modules\node-sass\lib\index.js:420:22)
    at SASSPlugin.compile (E:\___temp-projects\TBXSurfCSS\node_modules\angular-cli\lib\broccoli\angular-broccoli-sass.js:52:25)
    at E:\___temp-projects\TBXSurfCSS\node_modules\angular-cli\lib\broccoli\angular-broccoli-sass.js:32:14
    at Array.forEach (native)
    at SASSPlugin.build (E:\___temp-projects\TBXSurfCSS\node_modules\angular-cli\lib\broccoli\angular-broccoli-sass.js:28:22)
    at E:\___temp-projects\TBXSurfCSS\node_modules\angular-cli\node_modules\broccoli-caching-writer\index.js:152:21
    at lib$rsvp$$internal$$tryCatch (E:\___temp-projects\TBXSurfCSS\node_modules\angular-cli\node_modules\rsvp\dist\rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (E:\___temp-projects\TBXSurfCSS\node_modules\angular-cli\node_modules\rsvp\dist\rsvp.js:1048:17)
    at lib$rsvp$$internal$$publish (E:\___temp-projects\TBXSurfCSS\node_modules\angular-cli\node_modules\rsvp\dist\rsvp.js:1019:11)
    at lib$rsvp$asap$$flush (E:\___temp-projects\TBXSurfCSS\node_modules\angular-cli\node_modules\rsvp\dist\rsvp.js:1198:9)
    at nextTickCallbackWith0Args (node.js:420:9)
    at process._tickCallback (node.js:349:13)```

Is there any way to resolve this issue?

**Comment by aexmachina** [comment]
You need to use the `includePaths` [config option](https://github.com/aexmachina/ember-cli-sass#usage).

**Comment by chanakairugal** [comment]
Thanks ill give shot
