### ISSUE TITLE
config option extension ignored in addon

### ISSUE THREAD

**Issue by jnfingerle** [aexmachina/ember-cli-sass#127]
When using sass syntax in an addon I get a Broccoli error that a scss file couldn't be found:

I'm using ember 2.7.0 and node 6.3.1 on Windows. 

Example: https://github.com/jnfingerle/testsass

Steps to reproduce:

**shell:**

```
T:\>ember version --verbose
ember-cli: 2.7.0
http_parser: 2.7.0
node: 6.3.1
v8: 5.0.71.57
uv: 1.9.1
zlib: 1.2.8
ares: 1.10.1-DEV
icu: 57.1
modules: 48
openssl: 1.0.2h
os: win32 x64

T:\>npm --version
3.10.3

T:\>ember addon testsass
[...]


T:\>cd testsass

T:\testsass>ember install ember-cli-sass
[...]

T:\testsass>npm install ember-cli-sass --save
[...]
```

**changed index.js to:**

```
/* jshint node: true */
'use strict';

module.exports = {
  name: 'testsass',
  included: function(app) {
    this._super.included(app);
  }
};
```

**shell:**

```
T:\testsass>move tests\dummy\app\styles\app.css tests\dummy\app\styles\app.scss
        1 Datei(en) verschoben.

T:\testsass>mkdir addon\styles

T:\testsass>copy tests\dummy\app\styles\app.scss addon\styles\addon.scss
        1 Datei(en) kopiert.

T:\testsass>ember s
```

... everything runs as expected ...

**shell:**

```
T:\testsass>move addon\styles\addon.scss addon\styles\addon.sass
        1 Datei(en) verschoben.

T:\testsass>move tests\dummy\app\styles\app.scss tests\dummy\app\styles\app.sass
        1 Datei(en) verschoben.
```

**changed ember-cli-build.js to:**

```
/*jshint node:true*/
/* global require, module */
var EmberAddon = require('ember-cli/lib/broccoli/ember-addon');

module.exports = function(defaults) {
  var app = new EmberAddon(defaults, {
    sassOptions: {'extension': 'sass'}
  });

  /*
    This build file specifies the options for the dummy test app of this
    addon, located in `/tests/dummy`
    This build file does *not* influence how the addon or the app using it
    behave. You most likely want to be modifying `./index.js` or app's build file
  */

  return app.toTree();
};
```

**shell:**

```
T:\testsass>ember s

Just getting started with Ember? Please visit http://localhost:4200/ember-getting-started to get going

Livereload server on http://localhost:49152
Serving on http://localhost:4200/
The Broccoli Plugin: [SassCompiler] failed with:
Error: File not found: \addon.scss
in any of the following include paths:
  T:\testsass\tmp\sass_compiler-input_base_path-Ia7obcfN.tmp\0
    at Object.findFileSync (T:\testsass\node_modules\include-path-searcher\index.js:12:9)
    at SassCompiler.build (T:\testsass\node_modules\broccoli-sass-source-maps\index.js:62:31)
    at T:\testsass\node_modules\broccoli-caching-writer\index.js:149:21
    at lib$rsvp$$internal$$tryCatch (T:\testsass\node_modules\rsvp\dist\rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (T:\testsass\node_modules\rsvp\dist\rsvp.js:1048:17)
    at lib$rsvp$$internal$$publish (T:\testsass\node_modules\rsvp\dist\rsvp.js:1019:11)
    at lib$rsvp$asap$$flush (T:\testsass\node_modules\rsvp\dist\rsvp.js:1198:9)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)

The broccoli plugin was instantiated at:
    at SassCompiler.Plugin (T:\testsass\node_modules\broccoli-caching-writer\node_modules\broccoli-plugin\index.js:10:31)
    at SassCompiler.CachingWriter [as constructor] (T:\testsass\node_modules\broccoli-caching-writer\index.js:18:10)
    at new SassCompiler (T:\testsass\node_modules\broccoli-sass-source-maps\index.js:20:17)
    at T:\testsass\node_modules\ember-cli-sass\index.js:27:12
    at Array.map (native)
    at SASSPlugin.toTree (T:\testsass\node_modules\ember-cli-sass\index.js:24:34)
    at T:\testsass\node_modules\ember-cli\node_modules\ember-cli-preprocess-registry\preprocessors.js:184:26
    at Array.forEach (native)
    at processPlugins (T:\testsass\node_modules\ember-cli\node_modules\ember-cli-preprocess-registry\preprocessors.js:182:11)
    at module.exports.preprocessCss (T:\testsass\node_modules\ember-cli\node_modules\ember-cli-preprocess-registry\preprocessors.js:152:10)
```

**Comment by jnfingerle** [comment]
Ok, this seems to have happened between ember 2.5.0 and 2.7.0, which makes me none the wiser.

**Comment by jnfingerle** [comment]
FWIW, changing the socond line of index.js/sassOptions to

```
var options = (this.app && this.app.options && this.app.options.sassOptions) 
    || (this.parent && this.parent.app && this.parent.app.options && this.parent.app.options.sassOptions) 
    || {};
```

seems to patch it for this specific problem. I suspect, there is a general problem that needs some recursion to be thrown at it. But I'm not to deep into the inner workings of ember addons.

**Comment by aexmachina** [comment]
@stefanpenner does this seem like the right approach?

**Comment by aexmachina** [comment]
Closing due to inactivity. Please feel free to reopen.
