### ISSUE TITLE
error: ember install ember-cli-sass

### ISSUE THREAD

**Issue by quangv** [aexmachina/ember-cli-sass#128]
I get the following error while trying to install ember-cli-sass (ember-cli-sass 5.4.0)

```
Version "0.1.2" not compatible with "^0.1.3"
Error: Version "0.1.2" not compatible with "^0.1.3"
    at Object.<anonymous> (/home/quang/dev/org/client/node_modules/ember-cli-sass/node_modules/broccoli-merge-trees/node_modules/fs-tree-diff/node_modules/heimdalljs-logger/node_modules/heimdalljs/index.js:12:11)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/quang/dev/org/client/node_modules/ember-cli-sass/node_modules/broccoli-merge-trees/node_modules/fs-tree-diff/node_modules/heimdalljs-logger/dist/index.js:9:32)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
```

after the failed install, even `ember --version` gives the same error as above. I have to remove `ember-cli-sass` to get ember-cli working again.

I'm on:
```
ember-cli: 2.6.3
node: 4.4.7
os: linux x64
```

**Comment by quangv** [comment]
http://discuss.emberjs.com/t/error-while-installing-ember-cli-mirage/11307/3 - related to this

**Comment by stefanpenner** [comment]
removing node_modules, and reinstalling should address

**Comment by quangv** [comment]
@stefanpenner I think that works, Thanks!
