### ISSUE TITLE
Cannot read property 'project' of undefined

### ISSUE THREAD

**Issue by eddiesholl** [aexmachina/ember-cli-sass#129]
The recent new version 5.5.0 of ember-cli-sass is breaking in an ember CI build. This package is pulled in as a dependency of ember-cli-notifications, which requires ^5.2.1 of ember-cli-sass.

Not sure where the 5.5.0 release on npm came from, it doesn't seem to be out of this repo?

Is it possible there's a caller of ember-cli-sass not binding a function call correctly?

The relevent code is:

```
     options.outputFile = options.outputFile || this.project.name() + '.css';
 
     return options;
   },:

``` 

Stack trace:

TypeError: Cannot read property 'project' of undefined
    at Class.module.exports.sassOptions (/var/lib/jenkins/workspace/refresh develop build/node_modules/ember-cli-sass/index.js:59:47)
    at SASSPlugin.toTree (/var/lib/jenkins/workspace/refresh develop build/node_modules/ember-cli-sass/index.js:15:32)
    at /var/lib/jenkins/workspace/refresh develop build/node_modules/ember-cli-preprocess-registry/preprocessors.js:184:26
    at Array.forEach (native)
    at processPlugins (/var/lib/jenkins/workspace/refresh develop build/node_modules/ember-cli-preprocess-registry/preprocessors.js:182:11)
    at module.exports.preprocessCss (/var/lib/jenkins/workspace/refresh develop build/node_modules/ember-cli-preprocess-registry/preprocessors.js:152:10)
    at Class.Addon.compileStyles (/var/lib/jenkins/workspace/refresh develop build/node_modules/ember-cli/lib/models/addon.js:511:12)
    at Class.Addon.treeForAddon (/var/lib/jenkins/workspace/refresh develop build/node_modules/ember-cli/lib/models/addon.js:404:25)
    at Class._treeFor (/var/lib/jenkins/workspace/refresh develop build/node_modules/ember-cli/lib/models/addon.js:322:31)
    at Class.treeFor (/var/lib/jenkins/workspace/refresh develop build/node_modules/ember-cli/lib/models/addon.js:290:19)
    at /var/lib/jenkins/workspace/refresh develop build/node_modules/ember-cli/lib/broccoli/ember-app.js:446:20
    at Array.map (native)
    at EmberApp.addonTreesFor (/var/lib/jenkins/workspace/refresh develop build/node_modules/ember-cli/lib/broccoli/ember-app.js:444:30)
    at EmberApp._addonTree (/var/lib/jenkins/workspace/refresh develop build/node_modules/ember-cli/lib/broccoli/ember-app.js:819:36)
    at EmberApp._processedVendorTree (/var/lib/jenkins/workspace/refresh develop build/node_modules/ember-cli/lib/broccoli/ember-app.js:864:20)
    at EmberApp._processedExternalTree (/var/lib/jenkins/workspace/refresh develop build/node_modules/ember-cli/lib/broccoli/ember-app.js:895:21)
    at EmberApp.appAndDependencies (/var/lib/jenkins/workspace/refresh develop build/node_modules/ember-cli/lib/broccoli/ember-app.js:991:30)
    at EmberApp.javascript (/var/lib/jenkins/workspace/refresh develop build/node_modules/ember-cli/lib/broccoli/ember-app.js:1099:34)
    at EmberApp.toArray (/var/lib/jenkins/workspace/refresh develop build/node_modules/ember-cli/lib/broccoli/ember-app.js:1504:10)
    at EmberApp.toTree (/var/lib/jenkins/workspace/refresh develop build/node_modules/ember-cli/lib/broccoli/ember-app.js:1526:30)
    at module.exports (/var/lib/jenkins/workspace/refresh develop build/ember-cli-build.js:65:14)

**Comment by rwwagner90** [comment]
I'm also having this issue and I am confused as to why this repo is on 5.4.0 and npm is on 5.5.0. Did someone forget to merge their 5.5.0 changes in here?

**Comment by aexmachina** [comment]
This has been fixed in v5.5.1. This project doesn't have adequate tests, and I'm not using this project in an addon so it's easy to miss things like this. Does anyone want to submit a PR with some tests for the addon use case?

**Comment by rwwagner90** [comment]
@aexmachina I may be able to help out, but I'm not seeing tests in the repo. Where are they located?

**Comment by aexmachina** [comment]
That's precisely the problem :) This addon was created when addon support was first added to Ember. The next version of this addon should be created using `ember addon`, which will create the infrastructure for testing. All the code for this addon lives in index.js, so it won't be hard to move it into the new structure. It'd be awesome if you were up to the task 👍

**Comment by rwwagner90** [comment]
@aexmachina I can give it a shot
