### ISSUE TITLE
How works with .sass and .scss ?

### ISSUE THREAD

**Issue by villander** [aexmachina/ember-cli-sass#133]
Hi, i'm using `.sass` in my app

``` js
var app = new EmberApp(defaults, {
    sassOptions: {
      extension: 'sass'
    },
```

But, i'm too using a `addon` that use `.scss`. So when i run `ember s` i have this error.

```
Livereload server on http://localhost:49152
Serving on http://localhost:4200/
The Broccoli Plugin: [SassCompiler] failed with:
Error: File not found: /addon.sass
in any of the following include paths:
  /Users/flama/Projects/remoto-app/tmp/sass_compiler-input_base_path-U0F8TTG1.tmp/0
    at Object.findFileSync (/Users/flama/Projects/remoto-app/node_modules/ember-cli-sass/node_modules/broccoli-sass-source-maps/node_modules/include-path-searcher/index.js:12:9)
    at SassCompiler.build (/Users/flama/Projects/remoto-app/node_modules/ember-cli-sass/node_modules/broccoli-sass-source-maps/index.js:63:31)
    at /Users/flama/Projects/remoto-app/node_modules/ember-cli-sass/node_modules/broccoli-sass-source-maps/node_modules/broccoli-caching-writer/index.js:149:21
    at lib$rsvp$$internal$$tryCatch (/Users/flama/Projects/remoto-app/node_modules/ember-cli-sass/node_modules/broccoli-sass-source-maps/node_modules/rsvp/dist/rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (/Users/flama/Projects/remoto-app/node_modules/ember-cli-sass/node_modules/broccoli-sass-source-maps/node_modules/rsvp/dist/rsvp.js:1048:17)
    at lib$rsvp$$internal$$publish (/Users/flama/Projects/remoto-app/node_modules/ember-cli-sass/node_modules/broccoli-sass-source-maps/node_modules/rsvp/dist/rsvp.js:1019:11)
    at lib$rsvp$asap$$flush (/Users/flama/Projects/remoto-app/node_modules/ember-cli-sass/node_modules/broccoli-sass-source-maps/node_modules/rsvp/dist/rsvp.js:1198:9)
    at doNTCallback0 (node.js:407:9)
    at process._tickCallback (node.js:336:13)
```

**Comment by villander** [comment]
@aexmachina you can help me?

**Comment by aexmachina** [comment]
The addon should be using its own ember-cli-sass. What is the addon? Are they using [this method](https://github.com/aexmachina/ember-cli-sass#alternative-addon-usage).

**Comment by mschwenk** [comment]
@villander I'm not sure but I think the prblem might be that you are using .sass but the addon uses .scss. 
And as you don't have an addon.sass file the sasscompiler can not find it. 

Have you tried to tell the SassOptions to use "scss" as extension? Or provided a addon.sass file?

**Comment by aexmachina** [comment]
Closing due to inactivity. Please feel free to reopen.

**Comment by ohcibi** [comment]
Still an issue with e.g. current version of ember-table which has an `addon.scss` file and when the project is configured for `.sass` extension it fails to build because it cannot find `addon.sass`.

@aexmachina as I cannot find anything about it: is this supposed to work (i.e. having the app configured to use `.sass` while using an addon that uses `.scss` files)? Or did you actually never verified this to work in this combination? I wonder if its due to a misconfiguration in ember-table my project or the ember-cli-sass addon oO.
