### ISSUE TITLE
alternate addon usage doesn't work for dummy app?

### ISSUE THREAD

**Issue by shaunc** [aexmachina/ember-cli-sass#139]
I'm trying to follow: https://github.com/aexmachina/ember-cli-sass#alternative-addon-usage

I am having trouble loading the \<my-addon.scss\> file from tests/dummy/app/styles/app.scss:

```
File: /Volumes/Macintosh_HD/Users/shauncutts/src/ember-datagrid/tmp/sass_compiler-input_base_path-ZGIGWPMk.tmp/0/app/styles/app.scss (5)
The Broccoli Plugin: [SassCompiler] failed with:
Error: File to import not found or unreadable: ember-datagrid
Parent style sheet: /Volumes/Macintosh_HD/Users/shauncutts/src/ember-datagrid/tmp/sass_compiler-input_base_path-ZGIGWPMk.tmp/0/app/styles/app.scss
    at options.error (/Volumes/Macintosh_HD/Users/shauncutts/src/ember-datagrid/node_modules/node-sass/lib/index.js:292:26)

The broccoli plugin was instantiated at: 
    at SassCompiler.Plugin (/Volumes/Macintosh_HD/Users/shauncutts/src/ember-datagrid/node_modules/broccoli-plugin/index.js:7:31)
    at SassCompiler.CachingWriter [as constructor] (/Volumes/Macintosh_HD/Users/shauncutts/src/ember-datagrid/node_modules/broccoli-caching-writer/index.js:18:10)
    at new SassCompiler (/Volumes/Macintosh_HD/Users/shauncutts/src/ember-datagrid/node_modules/broccoli-sass-source-maps/index.js:20:17)
    at /Volumes/Macintosh_HD/Users/shauncutts/src/ember-datagrid/node_modules/ember-cli-sass/index.js:27:12
    at Array.map (native)
    at SASSPlugin.toTree (/Volumes/Macintosh_HD/Users/shauncutts/src/ember-datagrid/node_modules/ember-cli-sass/index.js:24:34)
    at /Volumes/Macintosh_HD/Users/shauncutts/src/ember-datagrid/node_modules/ember-cli/node_modules/ember-cli-preprocess-registry/preprocessors.js:184:26
    at Array.forEach (native)
    at processPlugins (/Volumes/Macintosh_HD/Users/shauncutts/src/ember-datagrid/node_modules/ember-cli/node_modules/ember-cli-preprocess-registry/preprocessors.js:182:11)
    at module.exports.preprocessCss (/Volumes/Macintosh_HD/Users/shauncutts/src/ember-datagrid/node_modules/ember-cli/node_modules/ember-cli-preprocess-registry/preprocessors.js:152:10)
```
Is there any "trick" to using it in the dummy app (e.g. include path?)?

**Comment by shaunc** [comment]
:( opps -- sorry: I had the paths wrong!
