### ISSUE TITLE
Addon usage: Error: File to import not found or unreadable: foundation

### ISSUE THREAD

**Issue by samselikoff** [aexmachina/ember-cli-sass#142]
Hi - thanks for this great addon!

I'm trying to follow the instructions to get this working in an addon. I'm following the foundation examples. My addon's included hook looks like this

```js
  included: function(/* app */) {
    this._super.included.apply(this, arguments);
  }
```

and the `ember-cli-build.js` looks like

```js
  var app = new EmberAddon(defaults, {
    sassOptions: {
      includePaths: [
        '/bower_components/foundation/scss'
      ]
    }
  });

```

In `/addon/styles/addon.scss` I'm putting

```scss
@import 'foundation'
```

and here's the error I'm getting:

```
➜  nmbl-foundation git:(master) ✗ ember build dist
Build failed.
File: /Users/sselikoff/Work/gui-new/nmbl-foundation/tmp/sass_compiler-input_base_path-M5hBK65U.tmp/0/addon.scss (3)
The Broccoli Plugin: [SassCompiler] failed with:
Error: File to import not found or unreadable: foundation
Parent style sheet: /Users/sselikoff/Work/gui-new/nmbl-foundation/tmp/sass_compiler-input_base_path-M5hBK65U.tmp/0/addon.scss
    at options.error (/Users/sselikoff/Work/gui-new/nmbl-foundation/node_modules/ember-cli-sass/node_modules/broccoli-sass-source-maps/node_modules/node-sass/lib/index.js:292:26)

The broccoli plugin was instantiated at:
    at SassCompiler.Plugin (/Users/sselikoff/Work/gui-new/nmbl-foundation/node_modules/ember-cli-sass/node_modules/broccoli-sass-source-maps/node_modules/broccoli-caching-writer/node_modules/broccoli-plugin/index.js:7:31)
    at SassCompiler.CachingWriter [as constructor] (/Users/sselikoff/Work/gui-new/nmbl-foundation/node_modules/ember-cli-sass/node_modules/broccoli-sass-source-maps/node_modules/broccoli-caching-writer/index.js:18:10)
    at new SassCompiler (/Users/sselikoff/Work/gui-new/nmbl-foundation/node_modules/ember-cli-sass/node_modules/broccoli-sass-source-maps/index.js:20:17)
    at /Users/sselikoff/Work/gui-new/nmbl-foundation/node_modules/ember-cli-sass/index.js:39:12
    at Array.map (native)
    at SASSPlugin.toTree (/Users/sselikoff/Work/gui-new/nmbl-foundation/node_modules/ember-cli-sass/index.js:36:34)
    at /Users/sselikoff/Work/gui-new/nmbl-foundation/node_modules/ember-cli/node_modules/ember-cli-preprocess-registry/preprocessors.js:184:26
    at Array.forEach (native)
    at processPlugins (/Users/sselikoff/Work/gui-new/nmbl-foundation/node_modules/ember-cli/node_modules/ember-cli-preprocess-registry/preprocessors.js:182:11)
    at module.exports.preprocessCss (/Users/sselikoff/Work/gui-new/nmbl-foundation/node_modules/ember-cli/node_modules/ember-cli-preprocess-registry/preprocessors.js:152:10)
```

Have I set everything up right? Also is this related to https://github.com/aexmachina/ember-cli-sass/issues/127?

**Comment by samselikoff** [comment]
I think in the past I've had my addon add bower packages to the host app, and then configure the host app to import those via `index.js`. Is this how I should be doing this? Is it possible for the addon to "ship" with the bower SASS without the host app needing it in its own bower.json?

**Comment by samselikoff** [comment]
I've narrowed it down to [this line](https://github.com/aexmachina/ember-cli-sass/blob/master/index.js#L29). I'm unable to set `options.includePaths`. I've tried in my addon's `ember-cli-build.js`, my addon's `index.js`, and my host app's `ember-cli-build.js`. Any suggestions?

**Comment by samselikoff** [comment]
Ok, I ended up getting things wired up by setting the values in my addon's `config/environment.js` file:

```js
/*jshint node:true*/
'use strict';

module.exports = function(/* environment, appConfig */) {
  return {
    sassOptions: {
      includePaths: ['node_modules/nmbl-foundation/bower_components/foundation/scss']
    }
  };
};
```

Is this correct? If so, I'm happy to update the docs.

**Comment by aexmachina** [comment]
That seems very strange to me. I'm definitely using ember-cli-build.js in my app. I'm not using this addon in an addon, so it'd be greatly appreciated for you look into improving this use case. I don't see any reason why the configuration should be different for apps or addons. Welcome your input on this one!

**Comment by samselikoff** [comment]
@runspired explained that I need to have my addon add the bower package to the parent. I was hoping there'd be a way to do this but it looks like there isn't at the moment.

Thanks for your feedback, I can close this for now!
