### ISSUE TITLE
Clean install

### ISSUE THREAD

**Issue by Kamaz87** [aexmachina/ember-cli-sass#152]
versions:
ember-cli: 2.8.0
node: 6.9.2
os: win32 x64

ember new app3
ember install ember-cli-sass with error:
```
ENOENT: no such file or directory, scandir 'd:\work\app3\node_modules\ember-cli-sass\node_modules\broccoli-sass-source-maps\node_modules\node-sass\vendor'
Error: ENOENT: no such file or directory, scandir 'd:\work\app3\node_modules\ember-cli-sass\node_modules\broccoli-sass-source-maps\node_modules\node-sass\vendor'
    at Error (native)
    at Object.fs.readdirSync (fs.js:951:18)
    at Object.getInstalledBinaries (d:\work\app3\node_modules\ember-cli-sass\node_modules\broccoli-sass-source-maps\node_modules\node-sass\lib\extensions.js:122:13)
    at foundBinariesList (d:\work\app3\node_modules\ember-cli-sass\node_modules\broccoli-sass-source-maps\node_modules\node-sass\lib\errors.js:20:15)
    at foundBinaries (d:\work\app3\node_modules\ember-cli-sass\node_modules\broccoli-sass-source-maps\node_modules\node-sass\lib\errors.js:15:5)
    at Object.module.exports.missingBinary (d:\work\app3\node_modules\ember-cli-sass\node_modules\broccoli-sass-source-maps\node_modules\node-sass\lib\errors.js:45:5)
    at module.exports (d:\work\app3\node_modules\ember-cli-sass\node_modules\broccoli-sass-source-maps\node_modules\node-sass\lib\binding.js:15:30)
    at Object.<anonymous> (d:\work\app3\node_modules\ember-cli-sass\node_modules\broccoli-sass-source-maps\node_modules\node-sass\lib\index.js:14:35)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
```

package.json:
```
    "broccoli-asset-rev": "^2.4.2",
    "ember-ajax": "^2.0.1",
    "ember-cli": "2.8.0",
    "ember-cli-app-version": "^1.0.0",
    "ember-cli-babel": "^5.1.6",
    "ember-cli-dependency-checker": "^1.2.0",
    "ember-cli-htmlbars": "^1.0.3",
    "ember-cli-htmlbars-inline-precompile": "^0.3.1",
    "ember-cli-inject-live-reload": "^1.4.0",
    "ember-cli-jshint": "^1.0.0",
    "ember-cli-qunit": "^2.1.0",
    "ember-cli-release": "^0.2.9",
    "ember-cli-sass": "6.1.1",
    "ember-cli-sri": "^2.1.0",
    "ember-cli-test-loader": "^1.1.0",
    "ember-cli-uglify": "^1.2.0",
    "ember-data": "^2.8.0",
    "ember-export-application-global": "^1.0.5",
    "ember-load-initializers": "^0.5.1",
    "ember-resolver": "^2.0.3",
    "ember-welcome-page": "^1.0.1",
    "loader.js": "^4.0.1"
```
Any action with ember show error.  
Some addons (like ember-tooltips) use **ember-cli-sass**, they are not installed, too.

What am I doing wrong?

**Comment by aexmachina** [comment]
What's in your `node_modules/node-sass/vendor` directory?

It's working for me on Mac. I'd say it's a problem with node-sass on Windows. Suggest you try:

```
npm cache clear
rm -rf node_modules
npm install
```

If you create a new directory, run `npm install node-sass` what's in the `vendor` directory?

**Comment by Kamaz87** [comment]
Directory `node_modules/node-sass/vendor` does not exist. After `npm install node-sass` in empty folder too.

```
bin
lib
scripts
src
test
binding.gyp
CHANGELOG.md
LICENSE
package.json
README.md
```

Maybe problem with Node.js?

**Comment by aexmachina** [comment]
I would post this issue to node-sass. There's often problems with node-sass
on different platforms because it's a compiled module.​

**Comment by mike-north** [comment]
Hate to harp on this, but maybe there's something we can do from within this library to mitigate some of the upstream issues in node-sass and libsass?

Most users are not very sensitive to specific sass compiler versions, and just want a reliable and basic experience that "just works".

**Comment by aexmachina** [comment]
I'm open to specific suggestions, but as it stands I'm comfortable with ember-cli-sass being a thin wrapper to node-sass.
