### ISSUE TITLE
Doesn't work for Node v. 8

### ISSUE THREAD

**Issue by JaronAndre** [aexmachina/ember-cli-sass#162]
Hi,

After upgrading to Node 8, I'm receiving this error when trying to build:

Error: Missing binding C:\**\node_modules\node-sass\vendor\win32-x64-57\binding.node
Node Sass could not find a binding for your current environment: Windows 64-bit with Node.js 8.x

Found bindings for the following environments:
  - Windows 64-bit with Node.js 7.x

This usually happens because your environment has changed since running `npm install`.
Run `npm rebuild node-sass --force` to build the binding for your current environment.
    at module.exports (C:\**\node_modules\node-sass\lib\binding.js:15:13)
    at Object.<anonymous> (C:\**\node_modules\node-sass\lib\index.js:14:35)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\**\node_modules\broccoli-sass-source-maps\index.js:5:16)
    

It looks like node-sass has recently been updated to support the new Node 8 so the dependencies for this project probably need to be updated.

Thank you

**Comment by aexmachina** [comment]
The latest version of node-sass is 4.5.3 within the semver range of broccoli-sass-source-maps, so you should get that if you `rm -rf node_modules/` and `npm install`
