### ISSUE TITLE
Module did not self-register (iojs)

### ISSUE THREAD

**Issue by Globegitter** [aexmachina/ember-cli-sass#20]
I am so close to using iojs! Just the last thing, it seems, that keeps it from running:
Installing/building the latest `3.1.0-beta` works fone but when running `ember serve` I get the following error:
```js
version: 0.1.12
Module did not self-register.
Error: Module did not self-register.
    at Error (native)
    at Module.load (module.js:341:32)
    at Function.Module._load (module.js:296:12)
    at Module.require (module.js:351:17)
    at require (module.js:370:17)
    at Object.<anonymous> (project/node_modules/ember-cli-sass/node_modules/broccoli-sass/node_modules/node-sass/lib/index.js:211:15)
    at Module._compile (module.js:446:26)
    at Object.Module._extensions..js (module.js:464:10)
    at Module.load (module.js:341:32)
    at Function.Module._load (module.js:296:12)
```

Once I remove `ember-cli-sass` I can start up the server. Any idea what the issue could be? Could it be on the ember-cli side? Or something to do with node-sass?

**Comment by aexmachina** [comment]
It's likely to be node-sass, have you tried removing node-modules and
reinstalling?  Pretty sure it's working for us on io.js

**Comment by Globegitter** [comment]
Hmm, getting the same error now after switching back to node.js. Tried `npm cache clean && rm -rf node_modules`. Let's see if I get any further with debugging.

**Comment by Globegitter** [comment]
Ok, got it working on node again. Trying iojs again.

**Comment by Globegitter** [comment]
Seems to be related to https://github.com/sass/node-sass/issues/627

**Comment by aexmachina** [comment]
I'm closing this issue because it's related to an upstream issue. Reopen if you think it's necessary.
