### ISSUE TITLE
Cannot read property 'options' of undefined

### ISSUE THREAD

**Issue by pedrokost** [aexmachina/ember-cli-sass#24]
```
❯ ember s                             
version: 0.2.0-beta.1
Cannot read property 'options' of undefined
TypeError: Cannot read property 'options' of undefined
    at Class.module.exports.sassOptions (/home/pedro/Finesce/code/floorplan_editor/node_modules/ember-cli-sass/index.js:34:17)
    at Class.module.exports.setupPreprocessorRegistry (/home/pedro/Finesce/code/floorplan_editor/node_modules/ember-cli-sass/index.js:45:45)
    at Object.module.exports.setupRegistry (/home/pedro/Finesce/code/floorplan_editor/node_modules/ember-cli/lib/preprocessors.js:43:16)
    at Class.Addon (/home/pedro/Finesce/code/floorplan_editor/node_modules/ember-cli/lib/models/addon.js:81:5)
    at new Class (/home/pedro/Finesce/code/floorplan_editor/node_modules/ember-cli/node_modules/core-object/core-object.js:16:17)
    at /home/pedro/Finesce/code/floorplan_editor/node_modules/ember-cli/lib/models/addons-factory.js:44:19
    at visit (/home/pedro/Finesce/code/floorplan_editor/node_modules/ember-cli/lib/utilities/DAG.js:23:3)
    at DAG.topsort (/home/pedro/Finesce/code/floorplan_editor/node_modules/ember-cli/lib/utilities/DAG.js:82:7)
    at AddonsFactory.initializeAddons (/home/pedro/Finesce/code/floorplan_editor/node_modules/ember-cli/lib/models/addons-factory.js:40:9)
    at Project.initializeAddons (/home/pedro/Finesce/code/floorplan_editor/node_modules/ember-cli/lib/models/project.js:310:36)
```

[This](https://github.com/aexmachina/ember-cli-sass/blob/master/index.js#L35)is the line causing problems

**Comment by aexmachina** [comment]
Have pushed a new version, that should be fixed now.
