### ISSUE TITLE
Error when trying to install on ember-cli 0.2.0

### ISSUE THREAD

**Issue by vmalloc** [aexmachina/ember-cli-sass#30]
Getting:
```
module.js:355
  Module._extensions[extension](this, filename);
                               ^
Error: Module did not self-register.
    at Error (native)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/private/tmp/blap/node_modules/ember-cli-sass/node_modules/broccoli-sass/node_modules/node-sass/lib/index.js:181:15)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
node-sass@1.2.3 postinstall: `node scripts/build.js`
Exit status 1
Error: node-sass@1.2.3 postinstall: `node scripts/build.js`
Exit status 1
    at EventEmitter.<anonymous> (/private/tmp/blap/node_modules/ember-cli/node_modules/npm/lib/utils/lifecycle.js:213:16)
    at EventEmitter.emit (events.js:110:17)
    at ChildProcess.<anonymous> (/private/tmp/blap/node_modules/ember-cli/node_modules/npm/lib/utils/spawn.js:14:12)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1008:16)
    at Process.ChildProcess._handle.onexit (child_process.js:1080:5)
```

**Comment by SebastianSzturo** [comment]
You need to specify the latest version of ember-cli-sass in your package.json (It's 3.1 right now).

**Comment by sgasser** [comment]
Thanks! Update solves the problem
