### ISSUE TITLE
Should not require `app/styles/app.scss` for Addons

### ISSUE THREAD

**Issue by alexdiliberto** [aexmachina/ember-cli-sass#52]
If I just wanted to simply use scss for my addon testing directory `tests/dummy/app/styles/app.scss` you can not currently do this as of the `beta.6` release without including an empty `app/styles/app.scss` file.

Thoughts?

**Comment by aexmachina** [comment]
Sorry, I don't understand the question. Can you be more specific?

**Comment by alexdiliberto** [comment]
@aexmachina So here's an example. I create a new addon and I `ember install ember-cli-sass`. Now, in my newly created addon, the only thing that I really want to use the sass for, is to write my dummy app and style it using the file `tests/dummy/app/styles/app.scss` (I don't need or want my app to utilize an `app/styles/app.scss` file...this should not even exist for my app because it doesn't need it)

Starting with release `beta.6` I can no longer do this workflow without adding a empty/dummy `app/styles/app.scss` file because `ember build` or `ember serve` will immediately throw an error and complain.

At a quick look, I believe this commit introduces the issue but I haven't really debugged enough to know for sure https://github.com/aexmachina/ember-cli-sass/commit/3022fa12efa11ee81e0444d810c1cebee180f08f

**Comment by aexmachina** [comment]
Hi @alexdiliberto, thanks for the details. I can't reproduce this behaviour, I have an addon and have added ember-cli-sass as a devDependency of the addon and don't get this error. Are you able to push something that illustrates the problem?

**Comment by alexdiliberto** [comment]
@aexmachina Using `"ember-cli-sass": "^4.0.0-beta.7"`

Creating new project
npm install --save-dev ember-cli-sass
ember b
error

```shell
alex@AlexBookPro: ~/temp/trash-proj on master [!]
$ ember v
version: 0.2.3
node: 0.12.2
npm: 2.7.6

alex@AlexBookPro: ~/temp/trash-proj on master [!]
$ ember b
version: 0.2.3
Build failed.
File not found: /app/styles/app.sass
in any of the following include paths:
  /Users/alex/temp/trash-proj/tmp/tree_merger-tmp_dest_dir-kJk5nw8z.tmp
Error: File not found: /app/styles/app.sass
in any of the following include paths:
  /Users/alex/temp/trash-proj/tmp/tree_merger-tmp_dest_dir-kJk5nw8z.tmp
    at Object.findFileSync (/Users/alex/temp/trash-proj/node_modules/ember-cli-sass/node_modules/broccoli-sass-source-maps/node_modules/include-path-searcher/index.js:12:9)
    at SassCompiler.<anonymous> (/Users/alex/temp/trash-proj/node_modules/ember-cli-sass/node_modules/broccoli-sass-source-maps/index.js:48:33)
    at lib$rsvp$$internal$$initializePromise (/Users/alex/temp/trash-proj/node_modules/ember-cli-sass/node_modules/broccoli-sass-source-maps/node_modules/rsvp/dist/rsvp.js:537:9)
    at new lib$rsvp$promise$$Promise (/Users/alex/temp/trash-proj/node_modules/ember-cli-sass/node_modules/broccoli-sass-source-maps/node_modules/rsvp/dist/rsvp.js:850:9)
    at SassCompiler.updateCache (/Users/alex/temp/trash-proj/node_modules/ember-cli-sass/node_modules/broccoli-sass-source-maps/index.js:39:10)
    at /Users/alex/temp/trash-proj/node_modules/ember-cli-sass/node_modules/broccoli-sass-source-maps/node_modules/broccoli-caching-writer/index.js:96:34
    at lib$rsvp$$internal$$tryCatch (/Users/alex/temp/trash-proj/node_modules/ember-cli-sass/node_modules/broccoli-sass-source-maps/node_modules/rsvp/dist/rsvp.js:489:16)
    at lib$rsvp$$internal$$invokeCallback (/Users/alex/temp/trash-proj/node_modules/ember-cli-sass/node_modules/broccoli-sass-source-maps/node_modules/rsvp/dist/rsvp.js:501:17)
    at lib$rsvp$$internal$$publish (/Users/alex/temp/trash-proj/node_modules/ember-cli-sass/node_modules/broccoli-sass-source-maps/node_modules/rsvp/dist/rsvp.js:472:11)
    at lib$rsvp$asap$$flush (/Users/alex/temp/trash-proj/node_modules/ember-cli-sass/node_modules/broccoli-sass-source-maps/node_modules/rsvp/dist/rsvp.js:1290:9)
```

**Comment by aexmachina** [comment]
Okay, great thanks. Now I can see the issue. I've pushed v4.0.0-beta.8 with
a fix.​

**Comment by alexdiliberto** [comment]
:+1:

**Comment by alexdiliberto** [comment]
Wait, now it doesn't generate dummy.css. Don't have time to look into it tonight. I'll check tomorrow

**Comment by aexmachina** [comment]
That's correct, it doesn't create dummy.css because there's no app.scss to
create it from.​

**Comment by MiracleBlue** [comment]
I have an app.scss in my dummy file, with content in it, and I'm not getting a dummy.css anywhere either.  Only vendor.css.  Using 4.0.0-beta.8

**Comment by ahmed1490** [comment]
any updates on this?

**Comment by aexmachina** [comment]
Yes this appears to be an issue with ember-cli, I'll create an issue over there.
