### ISSUE TITLE
File Not Found: app/styles/app.scss

### ISSUE THREAD

**Issue by jamesdixon** [aexmachina/ember-cli-sass#67]
Hi, 

I have an `app.scss` file located under `app/styles/app.css`, but whenever I run `ember server`, I receive the following error:

```
Error: File not found: app/styles/app.scss
in any of the following include paths:
  /Users/jamesdixon/Projects/scout/platform/business/web/tmp/broccoli_merge_trees-output_path-veln3PGt.tmp
    at Object.findFileSync (/Users/jamesdixon/Projects/scout/platform/business/web/node_modules/ember-cli-sass/node_modules/broccoli-sass-source-maps/node_modules/include-path-searcher/index.js:12:9)
    at SassCompiler.<anonymous> (/Users/jamesdixon/Projects/scout/platform/business/web/node_modules/ember-cli-sass/node_modules/broccoli-sass-source-maps/index.js:51:33)
    at lib$rsvp$$internal$$initializePromise (/Users/jamesdixon/Projects/scout/platform/business/web/node_modules/ember-cli-sass/node_modules/broccoli-sass-source-maps/node_modules/rsvp/dist/rsvp.js:541:9)
    at new lib$rsvp$promise$$Promise (/Users/jamesdixon/Projects/scout/platform/business/web/node_modules/ember-cli-sass/node_modules/broccoli-sass-source-maps/node_modules/rsvp/dist/rsvp.js:757:9)
    at SassCompiler.updateCache (/Users/jamesdixon/Projects/scout/platform/business/web/node_modules/ember-cli-sass/node_modules/broccoli-sass-source-maps/index.js:42:10)
    at /Users/jamesdixon/Projects/scout/platform/business/web/node_modules/ember-cli-sass/node_modules/broccoli-sass-source-maps/node_modules/broccoli-caching-writer/index.js:96:34
    at lib$rsvp$$internal$$tryCatch (/Users/jamesdixon/Projects/scout/platform/business/web/node_modules/ember-cli-sass/node_modules/broccoli-sass-source-maps/node_modules/rsvp/dist/rsvp.js:493:16)
    at lib$rsvp$$internal$$invokeCallback (/Users/jamesdixon/Projects/scout/platform/business/web/node_modules/ember-cli-sass/node_modules/broccoli-sass-source-maps/node_modules/rsvp/dist/rsvp.js:505:17)
    at lib$rsvp$$internal$$publish (/Users/jamesdixon/Projects/scout/platform/business/web/node_modules/ember-cli-sass/node_modules/broccoli-sass-source-maps/node_modules/rsvp/dist/rsvp.js:476:11)
    at lib$rsvp$asap$$flush (/Users/jamesdixon/Projects/scout/platform/business/web/node_modules/ember-cli-sass/node_modules/broccoli-sass-source-maps/node_modules/rsvp/dist/rsvp.js:1198:9)
    at process._tickCallback (node.js:355:11)
```

Here's my version info:

```
version: 1.13.8
node: 0.12.2
npm: 2.13.4
os: darwin x64
```
and my dependencies in `package.json`:

```javascript
  "devDependencies": {
    "broccoli-asset-rev": "^2.1.2",
    "dotenv": "1.2.0",
    "ember-cli": "1.13.8",
    "ember-cli-app-version": "0.5.0",
    "ember-cli-babel": "^5.1.3",
    "ember-cli-content-security-policy": "0.4.0",
    "ember-cli-dependency-checker": "^1.0.1",
    "ember-cli-deploy": "^0.4.2",
    "ember-cli-deploy-azure": "0.0.11",
    "ember-cli-dotenv": "1.0.0",
    "ember-cli-flash": "1.3.1",
    "ember-cli-htmlbars": "0.7.9",
    "ember-cli-htmlbars-inline-precompile": "^0.2.0",
    "ember-cli-ic-ajax": "0.2.1",
    "ember-cli-inject-live-reload": "^1.3.1",
    "ember-cli-less": "1.3.3",
    "ember-cli-mirage": "0.1.7",
    "ember-cli-mocha": "0.9.1",
    "ember-cli-release": "0.2.3",
    "ember-cli-sass": "4.1.0",
    "ember-cli-simple-auth": "0.8.0",
    "ember-cli-simple-auth-testing": "0.8.0",
    "ember-cli-simple-auth-token": "https://github.com/jamesdixon/ember-cli-simple-auth-token.git",
    "ember-cli-sri": "^1.0.3",
    "ember-cli-uglify": "^1.2.0",
    "ember-data": "1.13.8",
    "ember-deploy-redis": "0.0.6",
    "ember-disable-proxy-controllers": "^1.0.0",
    "ember-export-application-global": "^1.0.3",
    "ember-paper": "https://github.com/peec/ember-paper.git#feature/paper-menu",
    "ember-validations": "2.0.0-alpha.3"
  }
```

The weird thing is that if I create a fresh ember-cli project, I have no issues. Possibly a conflict with another dependency?

Appreciate your help!

Best,
James

**Comment by jamesdixon** [comment]
I ended up removing `ember-cli-less` to see if there was a conflict there and sure enough, as soon as I removed it, things started working. Are you aware of a way for these two to co-exist? Unfortunately, I have a template that uses a ton of LESS, but a couple of plugins that are using SASS. 

Thanks!

**Comment by aexmachina** [comment]
Maybe try specifying the `extension` option.

**Comment by jamesdixon** [comment]
No luck. I just went ahead and converted all the LESS files to SASS. I can leave this open if it becomes an issue for others or can close it if you'd prefer.

Thanks!
