### ISSUE TITLE
Not found file `.sass` 

### ISSUE THREAD

**Issue by villander** [aexmachina/ember-cli-sass#95]
**my ember cli sass in version 5.2.1 did not want to run .sass, does anyone know what to do?
he complains because they do not think the '.scss` but I am using a `.sass`**

``` 
remoto-app git:(feature/update-ember-cli) ✗ ember s
version: 1.13.13
Livereload server on http://localhost:49152
Serving on http://localhost:4200/
File not found: /app/styles/app.scss
in any of the following include paths:
  /Users/flama/Projects/remoto-app/tmp/sass_compiler-input_base_path-bFU50eg9.tmp/0
Error: File not found: /app/styles/app.scss
in any of the following include paths:
  /Users/flama/Projects/remoto-app/tmp/sass_compiler-input_base_path-bFU50eg9.tmp/0
    at Object.findFileSync (/Users/flama/Projects/remoto-app/node_modules/ember-cli-sass/node_modules/broccoli-sass-source-maps/node_modules/include-path-searcher/index.js:12:9)
    at SassCompiler.build (/Users/flama/Projects/remoto-app/node_modules/ember-cli-sass/node_modules/broccoli-sass-source-maps/index.js:61:31)
    at /Users/flama/Projects/remoto-app/node_modules/broccoli-caching-writer/index.js:142:21
    at lib$rsvp$$internal$$tryCatch (/Users/flama/Projects/remoto-app/node_modules/broccoli-caching-writer/node_modules/rsvp/dist/rsvp.js:493:16)
    at lib$rsvp$$internal$$invokeCallback (/Users/flama/Projects/remoto-app/node_modules/broccoli-caching-writer/node_modules/rsvp/dist/rsvp.js:505:17)
    at lib$rsvp$$internal$$publish (/Users/flama/Projects/remoto-app/node_modules/broccoli-caching-writer/node_modules/rsvp/dist/rsvp.js:476:11)
    at lib$rsvp$asap$$flush (/Users/flama/Projects/remoto-app/node_modules/broccoli-caching-writer/node_modules/rsvp/dist/rsvp.js:1198:9)
    at doNTCallback0 (node.js:407:9)
    at process._tickCallback (node.js:336:13)
```

**Comment by dukex** [comment]
Now by default ember-cli-sass use `.scss` file, to use `.sass` set the `extension` options

``` javascript
var app = new EmberApp({
  sassOptions: {
    extension: 'sass'
  }
});
```

**Comment by villander** [comment]
Thanks @dukex
